version: '3.8'

services:
  newsapi:
    image: newsapi
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: always